import { ResumeData } from '@shared/types';

export const initialResumeData: ResumeData = {
  id: 'resume-demo-1',
  title: 'Software Engineer Fresher',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  isFavorite: true,
  templateId: 'modern-clean',
  personal: {
    fullName: 'Alex Vance',
    jobTitle: 'Junior Full Stack Software Developer',
    email: 'alex.vance@example.com',
    phone: '+1 (555) 234-5678',
    location: 'San Francisco, CA',
    website: 'https://alexvance.dev',
    linkedin: 'https://linkedin.com/in/alexvance-dev',
    github: 'https://github.com/alexvance-dev',
    twitter: 'https://twitter.com/alexvance_dev',
    portfolio: 'https://alexvance.dev/portfolio',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    showPhoto: true,
    qrCodeUrl: 'https://alexvance.dev',
    showQrCode: true,
  },
  objective:
    'Enthusiastic Computer Science graduate with strong foundations in React, Node.js, TypeScript, and Data Structures. Seeking a Junior Software Engineer position to leverage problem-solving skills and contribute to scalable web products.',
  summary:
    'Passionate and detail-oriented Full Stack Developer with experience building modern web applications using React, TypeScript, Express, and modern styling toolkits. Proven track record in university capstone projects and internship experience delivering optimized RESTful APIs and responsive frontends.',
  education: [
    {
      id: 'edu-1',
      degree: 'Bachelor of Science in Computer Science',
      institution: 'State University of California',
      location: 'Berkeley, CA',
      startDate: '2021',
      endDate: '2025',
      isCurrent: false,
      gpa: '3.85 / 4.0 (Magna Cum Laude)',
      coursework: 'Data Structures, Algorithms, Web Engineering, Database Systems, Cloud Computing',
    },
  ],
  experience: [
    {
      id: 'exp-1',
      company: 'TechCorp Solutions',
      role: 'Full Stack Engineering Intern',
      location: 'San Jose, CA',
      startDate: 'Jun 2024',
      endDate: 'Sep 2024',
      isCurrent: false,
      description: 'Worked on modernizing customer dashboard applications.',
      bullets: [
        'Developed 12+ responsive UI components using React and TypeScript, reducing page load latency by 28%.',
        'Built 5 RESTful API endpoints with Express.js to process user analytics and database queries efficiently.',
        'Wrote comprehensive unit tests using Jest, boosting codebase test coverage from 65% to 84%.',
      ],
    },
  ],
  projects: [
    {
      id: 'proj-1',
      title: 'DevSync - Collaborative Code Workspace',
      subtitle: 'Real-time Code & Notes Sharing Platform',
      technologies: ['React', 'Node.js', 'Socket.io', 'TailwindCSS'],
      link: 'https://devsync-app.example.com',
      githubLink: 'https://github.com/alexvance-dev/devsync',
      startDate: 'Jan 2025',
      endDate: 'Mar 2025',
      bullets: [
        'Implemented WebSockets protocol for sub-100ms real-time multi-user document synchronization.',
        'Integrated Monaco Editor for rich syntax highlighting supporting over 15 programming languages.',
        'Deployed production frontend to Vercel and backend services to Render with CI/CD GitHub Actions.',
      ],
    },
    {
      id: 'proj-2',
      title: 'SmartResume AI - Resume Scoring Tool',
      subtitle: 'Automated Keyword & Metric Extraction',
      technologies: ['TypeScript', 'Express', 'React 19', 'TailwindCSS'],
      link: 'https://smartresume.example.com',
      githubLink: 'https://github.com/alexvance-dev/smartresume',
      startDate: 'Nov 2024',
      endDate: 'Dec 2024',
      bullets: [
        'Created a client-side ATS scoring engine measuring 10+ resume metrics with instant visual breakdown.',
        'Added PDF & DOCX client export capabilities with customizable document styling controls.',
      ],
    },
  ],
  skills: [
    {
      id: 'sk-cat-1',
      category: 'Frontend & UI',
      items: [
        { id: 'sk-1', name: 'React 19', level: 90 },
        { id: 'sk-2', name: 'TypeScript', level: 85 },
        { id: 'sk-3', name: 'TailwindCSS', level: 92 },
        { id: 'sk-4', name: 'Next.js', level: 75 },
        { id: 'sk-5', name: 'HTML5/CSS3', level: 95 },
      ],
    },
    {
      id: 'sk-cat-2',
      category: 'Backend & Databases',
      items: [
        { id: 'sk-6', name: 'Node.js', level: 85 },
        { id: 'sk-7', name: 'Express.js', level: 88 },
        { id: 'sk-8', name: 'REST APIs', level: 90 },
        { id: 'sk-9', name: 'MongoDB / PostgreSQL', level: 78 },
      ],
    },
    {
      id: 'sk-cat-3',
      category: 'Developer Tools',
      items: [
        { id: 'sk-10', name: 'Git & GitHub', level: 92 },
        { id: 'sk-11', name: 'Docker', level: 70 },
        { id: 'sk-12', name: 'Vite / Webpack', level: 82 },
      ],
    },
  ],
  softSkills: ['Problem Solving', 'Team Collaboration', 'Agile Methodology', 'Adaptability', 'Technical Communication'],
  certifications: [
    {
      id: 'cert-1',
      name: 'AWS Certified Cloud Practitioner',
      issuer: 'Amazon Web Services',
      issueDate: 'Aug 2024',
      expiryDate: 'Aug 2027',
      credentialId: 'AWS-99201948',
      url: 'https://aws.amazon.com/verify',
    },
    {
      id: 'cert-2',
      name: 'Meta Front-End Developer Professional Certificate',
      issuer: 'Meta / Coursera',
      issueDate: 'May 2024',
      expiryDate: 'Lifetime',
      credentialId: 'META-FE-88129',
      url: 'https://coursera.org/verify',
    },
  ],
  achievements: [
    {
      id: 'ach-1',
      title: 'First Place Winner - HackTech 2024',
      description: 'Awarded 1st place among 50+ university teams for building an AI-powered accessibility tool.',
      date: 'Oct 2024',
    },
    {
      id: 'ach-2',
      title: 'Dean’s Honor List',
      description: 'Maintained GPA above 3.8 for 6 consecutive academic semesters.',
      date: '2021 - 2024',
    },
  ],
  languages: [
    { id: 'lang-1', language: 'English', proficiency: 'Native / Bilingual' },
    { id: 'lang-2', language: 'Spanish', proficiency: 'Intermediate' },
  ],
  hobbies: ['Competitive Programming', 'Open Source Contributing', 'Tech Blogging', 'Chess'],
  strengths: ['Analytical Thinking', 'Rapid Learner', 'Clean Code Advocate', 'Self-Motivated'],
  references: [
    {
      id: 'ref-1',
      name: 'Dr. Robert Miller',
      position: 'Professor of Computer Science',
      company: 'UC Berkeley',
      email: 'rmiller@berkeley.edu',
      phone: '+1 (555) 987-6543',
    },
  ],
  declaration: {
    text: 'I hereby declare that all details provided in this resume are true and complete to the best of my knowledge.',
    place: 'San Francisco, CA',
    date: '2025-08-01',
    signatureUrl: '',
    showSignature: true,
  },
  customizations: {
    themeColor: '#2563EB',
    secondaryColor: '#7C3AED',
    accentColor: '#06B6D4',
    fontFamily: 'Inter',
    fontSize: 'md',
    lineHeight: 'normal',
    margin: 'normal',
    borderRadius: 'md',
    headerStyle: 'standard',
    sectionOrder: [
      'objective',
      'summary',
      'education',
      'experience',
      'projects',
      'skills',
      'softSkills',
      'certifications',
      'achievements',
      'languages',
      'hobbies',
      'references',
      'declaration',
    ],
    sectionVisibility: {
      objective: true,
      summary: true,
      education: true,
      experience: true,
      projects: true,
      skills: true,
      softSkills: true,
      certifications: true,
      achievements: true,
      languages: true,
      hobbies: true,
      references: true,
      declaration: true,
    },
    showIcons: true,
    backgroundStyle: 'white',
  },
};
