import { TemplateMetadata } from '@shared/types';

export const ALL_TEMPLATES: TemplateMetadata[] = [
  {
    id: 'modern-clean',
    name: 'Modern Clean',
    category: 'Modern',
    description: 'Sleek two-column header with crisp typography and subtle modern accents.',
    previewColor: '#2563EB',
    popular: true,
    recommendedFor: ['Full Stack Developer', 'Software Engineer', 'Frontend Engineer'],
  },
  {
    id: 'classic-prof',
    name: 'Classic Professional',
    category: 'Classic',
    description: 'Traditional single-column layout with elegant serif titles and crisp divider lines.',
    previewColor: '#1E293B',
    popular: true,
    recommendedFor: ['Academic', 'Finance', 'Law', 'Business Graduate'],
  },
  {
    id: 'executive-min',
    name: 'Executive Minimal',
    category: 'Executive',
    description: 'High-impact top header with structured modern grid alignment.',
    previewColor: '#7C3AED',
    recommendedFor: ['Product Manager', 'Business Analyst', 'Consultant'],
  },
  {
    id: 'corporate-elite',
    name: 'Corporate Elite',
    category: 'Executive',
    description: 'Structured corporate blocks with bold primary accents and metadata highlights.',
    previewColor: '#0F172A',
    recommendedFor: ['Corporate Executive', 'Management Trainee', 'HR Specialist'],
  },
  {
    id: 'minimal-fresh',
    name: 'Minimal Fresh',
    category: 'Minimal',
    description: 'Whitespace-centric design prioritizing content readability and clean typography.',
    previewColor: '#64748B',
    popular: true,
    recommendedFor: ['Fresher', 'Graduate', 'General Roles'],
  },
  {
    id: 'ats-master',
    name: 'ATS Master',
    category: 'Minimal',
    description: '100% ATS-optimized single column layout guaranteed for resume screening software.',
    previewColor: '#059669',
    popular: true,
    recommendedFor: ['All Software Roles', 'Enterprise Applications', 'Mass Recruiters'],
  },
  {
    id: 'google-tech',
    name: 'Google Tech Style',
    category: 'Tech',
    description: 'Inspired by Silicon Valley engineer resumes. Clean, bullet-focused, zero clutter.',
    previewColor: '#4285F4',
    popular: true,
    recommendedFor: ['Backend Engineer', 'AI/ML Engineer', 'Systems Programmer'],
  },
  {
    id: 'microsoft-azure',
    name: 'Microsoft Azure',
    category: 'Tech',
    description: 'Tech-focused layout featuring Azure blue headers, badge skill pills, and crisp section dividers.',
    previewColor: '#0078D4',
    recommendedFor: ['Cloud Engineer', 'DevOps', 'Cybersecurity Specialist'],
  },
  {
    id: 'amazon-leadership',
    name: 'Amazon Leadership',
    category: 'Tech',
    description: 'Emphasizes quantitative metrics, project outcomes, and technical leadership.',
    previewColor: '#FF9900',
    recommendedFor: ['Software Engineer', 'Technical Product Manager', 'Data Scientist'],
  },
  {
    id: 'startup-dynamo',
    name: 'Startup Dynamo',
    category: 'Tech',
    description: 'Vibrant modern header with floating tech stack badges and dynamic project cards.',
    previewColor: '#06B6D4',
    recommendedFor: ['Startup Engineer', 'Mobile Developer', 'Full Stack Dev'],
  },
  {
    id: 'creative-portfolio',
    name: 'Creative Portfolio',
    category: 'Creative',
    description: 'Left sidebar accent panel with timeline items and portfolio highlights.',
    previewColor: '#EC4899',
    popular: true,
    recommendedFor: ['UI/UX Designer', 'Graphic Designer', 'Content Creator'],
  },
  {
    id: 'elegant-serenity',
    name: 'Elegant Serenity',
    category: 'Creative',
    description: 'Soft rose & purple undertones with elegant line highlights and refined font kerning.',
    previewColor: '#D946EF',
    recommendedFor: ['Marketing Specialist', 'PR Associate', 'Event Manager'],
  },
  {
    id: 'simple-one-pager',
    name: 'Simple One-Pager',
    category: 'Minimal',
    description: 'Ultra-compact single page template specially tuned for university freshers.',
    previewColor: '#3B82F6',
    popular: true,
    recommendedFor: ['University Fresher', 'First Job Applicants', 'Internship Seekers'],
  },
  {
    id: 'designer-visual',
    name: 'Visual Designer',
    category: 'Creative',
    description: 'Visual skill meters, hero profile header, and rich project showcase grid.',
    previewColor: '#F59E0B',
    recommendedFor: ['Product Designer', 'Visual Artist', 'Animator'],
  },
  {
    id: 'developer-stack',
    name: 'Developer Stack',
    category: 'Tech',
    description: 'Terminal-inspired accent styling with code block tags and GitHub repository links.',
    previewColor: '#10B981',
    popular: true,
    recommendedFor: ['Open Source Contributor', 'Web Developer', 'DevOps Specialist'],
  },
  {
    id: 'engineer-core',
    name: 'Core Engineer',
    category: 'Tech',
    description: 'Clean engineering format focusing on technical certifications, core tools, and lab projects.',
    previewColor: '#2563EB',
    recommendedFor: ['Mechanical Engineer', 'ECE Engineer', 'Civil Engineer'],
  },
  {
    id: 'analyst-insights',
    name: 'Data Analyst Insights',
    category: 'Special',
    description: 'Dedicated analytics layout highlighting SQL, Python, Tableau, and data metrics.',
    previewColor: '#0891B2',
    recommendedFor: ['Data Analyst', 'BI Developer', 'Business Intelligence'],
  },
  {
    id: 'business-associate',
    name: 'Business Associate',
    category: 'Executive',
    description: 'Focus on strategic summary, core competencies grid, and internships.',
    previewColor: '#4338CA',
    recommendedFor: ['Business Operations', 'Sales Trainee', 'Marketing Associate'],
  },
  {
    id: 'medical-health',
    name: 'Medical & Clinical',
    category: 'Special',
    description: 'Clean medical formatting tailored for clinical rotations, certifications, and licenses.',
    previewColor: '#0D9488',
    recommendedFor: ['Nursing Graduate', 'Medical Resident', 'Healthcare Admin'],
  },
  {
    id: 'academic-research',
    name: 'Academic Research',
    category: 'Academic',
    description: 'Subtle academic layout for publications, thesis topics, lab experience, and GPA.',
    previewColor: '#475569',
    recommendedFor: ['Research Scholar', 'Master Student', 'Lab Assistant'],
  },
  {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    category: 'Modern',
    description: 'Refreshing cyan & deep blue gradient header with crisp icons.',
    previewColor: '#0284C7',
  },
  {
    id: 'emerald-green',
    name: 'Emerald Green',
    category: 'Modern',
    description: 'Rich emerald green theme with status badges and modern section tags.',
    previewColor: '#059669',
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    category: 'Modern',
    description: 'Deep violet accents with rounded skill pills and clean contact bar.',
    previewColor: '#7C3AED',
  },
  {
    id: 'dark-premium',
    name: 'Dark Slate Premium',
    category: 'Special',
    description: 'Contemporary high-contrast dark top bar with pristine white body text.',
    previewColor: '#1E293B',
    popular: true,
  },
  {
    id: 'luxury-gold',
    name: 'Luxury Champagne',
    category: 'Special',
    description: 'Sophisticated warm amber & gold accents for premium presentation.',
    previewColor: '#B45309',
  },
];
